export enum UserTypes {
  SIGN_UP = 'SIGN_UP',
  LOG_IN = 'LOG_IN',
  UPDATE = 'UPDATE',
  ERROR = 'ERROR',
  SPINNER = 'SPINNER',
  PINNED_COORDINATES = 'PINNED_COORDINATES',
  POST_SPOT = 'POST_SPOT',
  MATCH = 'MATCH',
  SAVE_CAR_PICTURE = 'SAVE_CAR_PICTURE',
  USER_SPOT_POSITION = 'USER_SPOT_POSITION',
}

export enum UserSpotPosition {
  DRIVER = 'DRIVER',
  PARKER = 'PARKER',
  UNKNOWN = 'UNKNOWN',
}
